version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - scbuildcodeunits
    aliases:
      - basebuildallcodeunits
      - bb

  BaseExampleStart:
    desc: "Base: Example start"
    silent: true
    dir: "./ClientInformation/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile"
    cmds:
      - python StartExample.py
    aliases:
      - baseexamplestart
      - beu

  BaseExampleStop:
    desc: "Base: Example stop"
    silent: true
    dir: "./ClientInformation/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile"
    cmds:
      - python StopExample.py
    aliases:
      - baseexamplestop
      - bed
